### ISSUE TITLE
IOS Error

### ISSUE THREAD

**Issue by rhb388** [TheAlphamerc/flutter_twitter_clone#101]
Built on iOS in Xcode and I’m receiving this update error after launching the app.

![0E47F5B1-C2A4-4B33-B805-B6FA8B520E45](https://user-images.githubusercontent.com/61764805/95041581-b9fd9280-069c-11eb-8ffc-9307ed49134d.png)

**Comment by rhb388** [comment]
It builds and works fine in the simulator but when uploaded to TestFlight, I get this update page when opened.

**Comment by TheAlphamerc** [comment]
@rhb388 This is screen is displaying because your app version code is not matched with current version code that you put under the firebase remote config.
This screen is not displayed on the simulator because I have added a condition to not displaying this screen on development mode. 
You can get rid of it either comment down code displaying on screenshot or just add app version code in firebase remote config
<img width="935" alt="Screenshot 2020-10-08 at 10 24 09 AM" src="https://user-images.githubusercontent.com/37103237/95417440-b135e680-0952-11eb-9942-d95a99efd769.png">
