### ISSUE TITLE
can I deploy this app as a website?

### ISSUE THREAD

**Issue by twepl** [TheAlphamerc/flutter_twitter_clone#127]
can I deploy this app as a website.
I also wonder if the template works on different screen resolutions, from tablet to phone?

**Comment by TheAlphamerc** [comment]
Yes, you can deploy the code on the web but not sure if all used plugins are compatible. Regarding screen resolution, I don't think there might be a problem.

**Comment by DovAzencot** [comment]
> Yes, you can deploy the code on the web but not sure if all used plugins are compatible. Regarding screen resolution, I don't think there might be a problem.

Did you succeed to run the app on the web? Currently trying without much success

**Comment by TheAlphamerc** [comment]
No, I haven't tried it yet.

**Comment by DovAzencot** [comment]
> No, I haven't tried it yet.

Well I've finally managed to do it. There was many issue due to usage of firebase library not available on the web yet, and some other issue. 

here is the link. https://social-dov.web.app/#/

I would also be interested by what is the consumption of reads/writes of the app on firebase. I assume the more registered users / tweets which have been made, the more a new user will consumn of reads as you have to search through all of the users / tweets? 
Can you share for example the consumption of the demo app on google play? 
Thanks !

**Comment by TheAlphamerc** [comment]
I am glad to see that you have managed to run the project for the web. In regarding the read/write consumption I agree with you it will increase with no. of users. But I think the firebase free plan has enough for quota for testing purpose.
Below is the screenshot of read/write operation on firebase current demo app available on play store.

<img width="876" alt="Screenshot 2020-12-21 at 12 57 54 PM" src="https://user-images.githubusercontent.com/37103237/102750966-dc927400-438c-11eb-9393-edf8190631a8.png">

**Comment by sayemmh** [comment]
@dovazencot would you mind sharing your steps to get your flutter clone up on the web? or even open source some of your application?

**Comment by DovAzencot** [comment]
Well I've changed the app quite a bit from what it was. Contact me via discord CryptoMasterFr#5250 if you more information.

**Comment by HoracioLopezCarvajal** [comment]
Hello, we want to convert it to a website and we have been stuck for 2 weeks, could you please tell us how you did a greeting

**Comment by giylo** [comment]
Please make the green tick on the Fwitter Clone app larger, please update the tick to be big.
