### ISSUE TITLE
App work slow on Android device

### ISSUE THREAD

**Issue by qwerty684** [TheAlphamerc/flutter_twitter_clone#141]
@TheAlphamerc  App work slow on android devices, when I scroll on feed page is lags, but on iOS devices working fine.. How to make this to load faster.. 
And what you think to implement  ` flutter_advanced_networkimage: ^0.7.0` to  preload Images Into Cache ?

**Comment by TheAlphamerc** [comment]
Hi @qwerty684 , In the beginning I had used `flutter_advanced_networkimage` package for image caching but due to some reason I removed this package but it was a long time ago and now I didn't remember the why I removed it. I think you can try this package and can check if it helps in improve performance.
