### ISSUE TITLE
Open chat screen when notification is added

### ISSUE THREAD

**Issue by karambitmonger** [TheAlphamerc/flutter_twitter_clone#155]
@TheAlphamerc 
Hi Sonu,could you help me with code that can redirect a user to the chat screen when he clicks on a notification. The current one just opens the app but does not redirect. I ahve been trying for a while now but i have not been succesful.

**Comment by TheAlphamerc** [comment]
@karambitmonger This feature was working earlier and stoped few month ago due to some complexities. Since Now I have normalised  the push notification code and created an independent push notification service so its working fine. Take a pull from repo and feel free to test this functionality and let me know if you face any issue in this.
