### ISSUE TITLE
What is the usage of URI.PARSE?

### ISSUE THREAD

**Issue by ublockme** [TheAlphamerc/flutter_twitter_clone#162]
Hi brother! I have a doubt. Just doubt 😬
What is the usage of ```link: Uri.parse('https://twitter.com/$id')``` in utility.dart file? Why you mentioned twitter.com here?

**Comment by TheAlphamerc** [comment]
It is meant to be used for dynamic link. When user open dynamic url on web browser on desktop this link redirect user to specified website. Since I didn't have specific website for Fwitter so therefor I used  Twitter's website url. For more information about  `link` check doc [here](https://pub.dev/documentation/firebase_dynamic_links/latest/firebase_dynamic_links/DynamicLinkParameters/link.html).

**Comment by ublockme** [comment]
Ok got it. 
When we activate dynamic link like ```fwitter.page.link``` in firebase, firebase asking us to give website address to create professional dynamic link such as ```https://fwitter.com/$path``` , so if we give our website url to generate professional look dynamic link in firebase then we need to add that url in our uri.parse too right?

**Comment by TheAlphamerc** [comment]
Its not just for professional look. This link works in two ways :- 
### On Mobile device
When dynamic link in clicked on mobile device it search for linked app which can open this link [Not talking about browser]. If no app found then it opens the play store to install the app.

### On Computer
On link clicked it directly open the provided url  on browser.

**Comment by ublockme** [comment]
Oh ok brother now i got it. Thanks
