### ISSUE TITLE
Issue with WillPopScope()

### ISSUE THREAD

**Issue by ruepay** [TheAlphamerc/flutter_twitter_clone#32]
There's an issue with WillPopScope() in several places. mainly at back button from chatscreen.

**Comment by TheAlphamerc** [comment]
The issue is occurring probably due to the null value of  `_chatUserList`. Add  null check on `_chatUserList` in dispose method as we added null check for `_messageList` in ChatState class.
This class is located at `lib/state/chats/chatState.dart`

<img width="1134" alt="Screenshot 2020-05-10 at 6 16 57 PM" src="https://user-images.githubusercontent.com/37103237/81499674-cbf42880-92ea-11ea-876f-7ee656cb3954.png">
