### ISSUE TITLE
Profile Pic Bug

### ISSUE THREAD

**Issue by teloanus** [TheAlphamerc/flutter_twitter_clone#80]
sir. is this issues clear already ? "Profile Picture bug ".
because i still got the problem. for example. when we upload the new profile picture then we post a tweet. then on the recent tweet will show our new profile picture which is correct, while in the old post.. the profile picture still shows the old one. I mean why it doesn't change for all automatically. Thanks sir.

**Comment by TheAlphamerc** [comment]
@teloanus This is a known issue right now. The profile picture is not updated in old tweets because when user creates a tweet his name, profile picture URL is saved with tweets information in db and in new tweets it gets new profile URL. 
<img width="804" alt="Screenshot 2020-08-08 at 11 34 23 AM" src="https://user-images.githubusercontent.com/37103237/89703741-2bee7f80-d96b-11ea-8bea-794ace6166c2.png">

#### How to fix this
This issue can be fix if user info can fetched from `profile` table instaed of getting in from user object which is saved in tweet itse

The disadvantage of getting user info for every tweet is that it will create several active connections with database and leads to slow app performance.

**Comment by TheAlphamerc** [comment]
For workaround user updated information can be taken from the search state. 
Add below code in `lib/widgets/tweet/tweet.dart` under build method.

``` dart
   final searchState = Provider.of<SearchState>(context, listen: false);
    model.user.profilePic = searchState.userlist.firstWhere((x) => x.userId == model.user.userId).profilePic;
```
<img width="1680" alt="Screenshot 2020-08-12 at 10 19 20 AM" src="https://user-images.githubusercontent.com/37103237/89976271-9d893f00-dc85-11ea-950d-a44fd98876df.png">

**Comment by emiravdovic** [comment]
@TheAlphamerc  can we make that this change in real time, now work just when we close app and reopen?

**Comment by TheAlphamerc** [comment]
@emiravdovic to make it realtime you can add pull to refresh functionality on the search page. Once you refresh user's list it will update the profile pic
